### ISSUE TITLE
Improve Floppy Controller

### ISSUE THREAD

**Issue by chschnell** [copy/v86#1362]
I'm currently working on [floppy.js](https://github.com/copy/v86/blob/master/src/floppy.js), the issues I'm aiming to fix:

* support [Windows 98](https://github.com/copy/v86/issues/1003), [Windows 2000](https://github.com/copy/v86/issues/1063) and W2k3
* support second floppy drive `fdb`
* support format command

In the past weeks, whenever I found a few hours here and there, I've been reading through floppy.js, the qemu implementation [fdc.c](https://github.com/qemu/qemu/blob/master/hw/block/fdc.c) which I use as reference, and whatever I could find on the Internet about the Intel 82078 Floppy Disk Controller which qemu implements.

So far I've added a bunch of boilerplate code to floppy.js and split off a new class `FloppyDrive` from `FloppyController` to allow for multiple drives, and similar to what I did with the IDE controller, I've refactored many literal constants to named constants and improved logging.

It's still too early for a PR, but are there any other known issues around the Floppy Disk Controller?

**Comment by chschnell** [comment]
I now have floppy support for Windows Server 2003 (issue #1358):

<img width="1024" height="768" alt="Image" src="https://github.com/user-attachments/assets/2f7bf6ce-7808-4eb2-a930-b17f5897d5bd" />

To get this to work I had to rewrite large parts of floppy.js (there was a lot of skeleton code), the Windows 2k3 (NT kernel) is quite sophisticated here.

I ran `make all-tests` and manually tested these guest OSes so far (all tests passed):

- MS-DOS 6.22
- FreeDOS 1.4
- Windows 3.1
- Windows 95
- Windows 2k3
- Debian 12

All guests (except Win31 which was booted from FDA) were booted from HDA and the floppy disk was inserted into the drive after boot.

There's going to be a breaking change for v86 state snapshot images where the floppy controller was snapshotted in non-idle state, meaning when it was in the middle of executing a floppy command. The runtime states differ too much in this case to map from the old snapshot representation to the one I need in the new representation. Maybe that's not a big deal, I don't know.

**Comment by chschnell** [comment]
Branch: https://github.com/chschnell/v86/tree/fix-fdc
You can test it at: https://www.rekoba.de/~cs/v86/demo/

I can't find any Win98 or Win2000 images for v86 to download, I'd really like to test them. Should I build them myself? Or maybe someone has some links?

**Comment by copy** [comment]
> I can't find any Win98 or Win2000 images for v86 to download, I'd really like to test them. Should I build them myself? Or maybe someone has some links?

Here you go: copy.sh/tmp/windows2k-v2.img.zst copy.sh/tmp/windows98.img.zst

**Comment by chschnell** [comment]
> > I can't find any Win98 or Win2000 images for v86 to download, I'd really like to test them. Should I build them myself? Or maybe someone has some links?
> 
> Here you go: copy.sh/tmp/windows2k-v2.img.zst copy.sh/tmp/windows98.img.zst

Perfect, thanks!

Only Windows 98 seems a bit unstable here, anything special to consider regarding RAM/BIOS/ACPI settings? EDIT: never mind, works now.

**Comment by chschnell** [comment]
Lookie, lookie: `fdb`!

#### Debian 12:

```bash
root@debian:~# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
fd0      2:0    1    4K  0 disk
fd1      2:1    1    4K  0 disk
sda      8:0    0    2G  0 disk
└─sda1   8:1    0    2G  0 part /
sr0     11:0    1 1024M  0 rom
```

#### Windows Server 2003:

<img width="1024" height="768" alt="Image" src="https://github.com/user-attachments/assets/999d8f51-e20d-449d-bc0b-cce972ee53f0" />

#### Windows 2000:

<img width="1024" height="768" alt="Image" src="https://github.com/user-attachments/assets/7d459036-536d-4930-93fe-f3a74da76337" />

**NOTE:** The window on the upper left shows drive `B:`, and the one on the lower right shows that the floppy controller support for **Windows 2000 is fixed (issue #1063)**.

#### EDIT: Windows 98:

<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/a7bb96d1-68ba-40bf-ac5f-ed46ab4b4731" />

**NOTE:** I had to run *Add new Hardware* from the control panel to add drive `B:`. This also shows that the floppy controller support for **Windows 98 is fixed (issue #1003)**.

#### EDIT 2: Windows 1.01:

<img width="640" height="350" alt="Image" src="https://github.com/user-attachments/assets/e3d9a366-8942-489c-931a-4019acee6af2" />

**Comment by chschnell** [comment]
Added insert/eject `fdb` into the user interface of my [demo](https://www.rekoba.de/~cs/v86/demo/), here's w2k3 with both `fda` and `fdb` loaded (floppy disks are FreeDOS1.4 and Windows1.01, respectively):

<img width="1024" height="768" alt="Image" src="https://github.com/user-attachments/assets/d48b3611-297a-4371-9f9d-9036f288fc2a" />

**Comment by DressedAlarm184** [comment]
@chschnell I've been using a fork of your v86 repo to enable the CI action to test the floppy drive B support in my private Windows 2.03 emulator. Your "further code cleanup" commit results in an error when building.

EDIT 1: Still doesn't build (same error too) with the newest "added support for floppy disk formatting" commit too 

<img width="1516" height="752" alt="Image" src="https://github.com/user-attachments/assets/40e119bb-14a4-4533-920b-d1f0763ebf9a" />

**Comment by chschnell** [comment]
> [@chschnell](https://github.com/chschnell) I've been using a fork of your v86 repo to enable the CI action to test the floppy drive B support in my private Windows 2.03 emulator. Your "further code cleanup" commit results in an error when building.
> 
> EDIT 1: Still doesn't build (same error too) with the newest "added support for floppy disk formatting" commit too

@DressedAlarm184: Thanks for reporting, I've fixed this bug in the latest commit and `make all-tests` now runs fine again here.

**Comment by chschnell** [comment]
Formatting floppies seems to work now.

So far I've tested with FreeDOS 1.4 (`format a:`), Debian 12 (`mkfs.msdos /dev/fd0`) and Windows Server 2003 (through the GUI, tested both Quick format and Full format because they work a bit differently).

I can use an unformatted, blank floppy disk image file when formatting, so a *create empty disk* function could be added now to the v86 web UI similar to the hard disks.

For a demo, here's a full format of a 1.44M disk (FreeDOS boot disk) under Windows Server 2003:

https://github.com/user-attachments/assets/1f9c52da-37e7-448d-a4c5-6d7e146d4e30

**Comment by chschnell** [comment]
@DressedAlarm184: branch [chschnell/v86:fix-fdc](https://github.com/chschnell/v86/tree/fix-fdc) that you forked off is now stale and will not receive further updates, please move to new branch **[chschnell/fix-floppy-controller](https://github.com/chschnell/v86/tree/fix-floppy-controller)**. I'd like to delete the old branch.

**Comment by DressedAlarm184** [comment]
@chschnell Okay, I have renamed the fix-fdc branch to fix-floppy-controller.

**Comment by PTz0uAH** [comment]
@chschnell I tested the changed Floppy.js with latest v86 and my Win98se image and must say "It works!"..

<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/1d3df8ff-78a1-4a6b-817f-11eee68a32ff" />

but the floppydrives still work under msdos compatibility mode and device manager ignores them..

<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/6b9db8ed-e92c-4de2-bf19-7d39be1563c2" />

any ideas how to get Devicemanager showing those drives?

**Comment by chschnell** [comment]
> any ideas how to get Devicemanager showing those drives?

Did you see my remark where I posted about Win98 SE:

> #### EDIT: Windows 98:
> <img alt="Image" width="640" height="480" src="https://private-user-images.githubusercontent.com/3799645/464289292-a7bb96d1-68ba-40bf-ac5f-ed46ab4b4731.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMzNjk5NzIsIm5iZiI6MTc1MzM2OTY3MiwicGF0aCI6Ii8zNzk5NjQ1LzQ2NDI4OTI5Mi1hN2JiOTZkMS02OGJhLTQwYmYtYWM1Zi1lZDQ2YWI0YjQ3MzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDcyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA3MjRUMTUwNzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzNjN2Q0NDRmMTZiZDIwOGZhNmRiMWY1ZTYxMTNmMGEzODRmMzZiNzAwMzY0YjhhODIxZjg0NTEwYzhhNjFlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Nmq6MjFuzz0M20FXfoyQn9oOMmfu24vTWN2iD_r0yyY">
> 
> **NOTE:** I had to run _Add new Hardware_ from the control panel to add drive `B:`. This also shows that the floppy controller support for **Windows 98 is fixed (issue [#1003](https://github.com/copy/v86/issues/1003))**.

You might also just try hitting _Refresh_ in the device manager, or try to reboot (that was neccessary under W2k to get rid of all glitches).

**Comment by PTz0uAH** [comment]
@chschnell it's great those floppy drives are working now.. superb!

Couldn't test it on your demo site though (not working)..

So I had to build an experimental version.. and test it overhere on the local wasm-enabled "tinyweb" server..

Furthermore after the "on-device-installed-like-a-breeze" Win2K3 I also succeeded in installing Win98SE right in v86..

The "on-v86-device" installation was absorbing a lot of time and even brought back the memories of how frustrating it was back in the day sometimes with dodgy hardware.. using the right bootfloppy and specific params was the key.. `win98/setup /C /ie /iv` and trying to install otherwise failed 100% of the time..

Nevertheless I succeeded, albeit conquering those BSODs is not for the normal end-user.. so a step by step manual that works for everyone is not possible yet.. there are too many factors involved.. therefore one has to be very lucky indeed.. :-)

Now I understand also why using QEMU is adviced.. as a workaround for some of the hardware quirks of v86.. 

Nevertheless I always prefer a local install.. yet the rate of success with Win9x highly depends on the machine and browser (i7 32gb + latest Chrome on Win10 64bit gave best results for me)..

I also tested the ramdisk-B:-dependable XP+ PE "hobby" builds and those are showing also 2 floppydrives available and while the Ramdisk is correctly getting the B: letter assigned the FDB is pushed forward in the enumeration.. so got C: (plus removable drive) assigned to it in a hdd-less live-cd setup..

As a workaround I disabled the B: drive in floppy.js and now I thought I could work with it the way I like it.. but now Win98SE hangs..

You already provided the hints in the code so I just used `new FloppyDrive(this, 1, fdc_config?.fdb, fdb_image, CMOS_FDD_TYPE_NO_DRIVE)` and that worked seemingly fine for my experimental fork to disable FDB.. but now I cannot use A: anymore.. it shows the content and freezes.. so I guess I did something wrong and more FDB code needs to be disabled probably but for now I revert to the "working version"..

BTW with nothing disabled in your floppy.js the drive A: works fine but one thing that would be rather handy.. (if changed..autosave when eject?).. if booting v86 without floppy and later insert a disk.. I could write to it yet not save the fdd-image for there is no "get floppy" button.. or can I perhaps use some JS code to save the disk anyway?

"Thanks and keep up the good work!"

**Comment by chschnell** [comment]
> [@chschnell](https://github.com/chschnell) it's great those floppy drives are working now.. superb!
> 
> Couldn't test it on your demo site though (not working)..
> 

Hmm, but it should work. Does this boot for you: https://www.rekoba.de/~cs/v86/demo/?p=hd_freedos14_20m_en (tested with current FireFox and Chrome)?

> So I had to build an experimental version.. and test it overhere on the local wasm-enabled "tinyweb" server..
> 

Nice!

> Furthermore after the "on-device-installed-like-a-breeze" Win2K3 I also succeeded in installing Win98SE right in v86..
> 
> The "on-v86-device" installation was absorbing a lot of time and even brought back the memories of how frustrating it was back in the day sometimes with dodgy hardware.. using the right bootfloppy and specific params was the key.. `win98/setup /C /ie /iv` and trying to install otherwise failed 100% of the time..
> 
> Nevertheless I succeeded, albeit conquering those BSODs is not for the normal end-user.. so a step by step manual that works for everyone is not possible yet.. there are too many factors involved.. therefore one has to be very lucky indeed.. :-)
> 

Win95/98 are the most unstable for me, I don't have anywhere near as many problems with the other guest OSes. Note that I do not use the VBE graphics drivers as they make it worse.

> Now I understand also why using QEMU is adviced.. as a workaround for some of the hardware quirks of v86..
> 
> Nevertheless I always prefer a local install.. yet the rate of success with Win9x highly depends on the machine and browser (i7 32gb + latest Chrome on Win10 64bit gave best results for me)..
> 

I don't think I've ever found Win95/98 install media that allowed for a pure v86 installation (without qemu), I'm using pre-build images for both.

> I also tested the ramdisk-B:-dependable XP+ PE "hobby" builds and those are showing also 2 floppydrives available and while the Ramdisk is correctly getting the B: letter assigned the FDB is pushed forward in the enumeration.. so got C: (plus removable drive) assigned to it in a hdd-less live-cd setup..
> 
> As a workaround I disabled the B: drive in floppy.js and now I thought I could work with it the way I like it.. but now Win98SE hangs..
> 
> You already provided the hints in the code so I just used `new FloppyDrive(this, 1, fdc_config?.fdb, fdb_image, CMOS_FDD_TYPE_NO_DRIVE)` and that worked seemingly fine for my experimental fork to disable FDB.. but now I cannot use A: anymore.. it shows the content and freezes.. so I guess I did something wrong and more FDB code needs to be disabled probably but for now I revert to the "working version"..
> 

This fda-only workaround that you describe works, tested with: FreeDOS 1.4, Win1.01, Win3.1, Win95, Win2k3 and Debian 12.

BUT it fails with Win98 SE (blocks when accessing a folder on the disk, as you describe). I was unsure, ran a bunch of tests (using the first commit of my PR) and found out that **the PR never worked with Win98 (!)**, it always blocks, I obviously failed to test it properly in the past (probably because booting it is so unstable, and also because it boots so slow).

> BTW with nothing disabled in your floppy.js the drive A: works fine but one thing that would be rather handy.. (if changed..autosave when eject?).. if booting v86 without floppy and later insert a disk.. I could write to it yet not save the fdd-image for there is no "get floppy" button.. or can I perhaps use some JS code to save the disk anyway?
> 

The interface between class `FloppyController` and v86 is still TODO, but here's what you can do: class `FlopyyDrive` has a method `get_buffer()`, it returns the disk's current `Uint8Array` object or `null` (if no disk is inserted). Here's an example "Save as..." method for an Uint8Array:

```javascript
function save_file_as(prompt_text, filename, buffer)
{
    if(!buffer)
    {
        return;
    }
    filename = prompt(prompt_text, filename);
    if(filename)
    {
        const array_buffer_url = window.URL.createObjectURL(new Blob([buffer]));
        const a = document.createElement('a');
        a.setAttribute('href', array_buffer_url);
        a.setAttribute('download', filename);
        a.setAttribute('downloadurl', `application/octet-stream:${filename}:${array_buffer_url}`);
        a.dispatchEvent(new MouseEvent('click'));
        window.URL.revokeObjectURL(array_buffer_url);
    }
}
```

Example:

```javascript
const vm = new V86({ ... });

// ...

const buffer = vm.v86.cpu.devices.fda.get_buffer();
save_file_as("Enter file name", "default.img", buffer);
```

> "Thanks and keep up the good work!"

You're welcome!

**Comment by PTz0uAH** [comment]
@chschnell  some progress..

About your site.. `Does this boot for you`: Yes it works if I use a Win 10 machine.. seems that Firefox ESR/Win7 on my laptop errors on `indexedDB.databases function missing`.. 

`@Win98se`: your commit dóés partly work for a specific situation.. if you remove the floppy controller from devicemanager and reboot.. in contrairy to the v86 mainstream version.. now I can use the A: drive "normally" from the desktop.. instead of going to dos first to be able to access the floppy from desktop.. normal access did not work most of the time before your floppy.js patch but I might be wrong on that.. btw msdos compatibility mode for A: and B: has as result that win98se feels more stable now but still might have other quirks..
 
`probably because booting it is so unstable, and also because it boots so slow`

Please explain slow.. this is my on-device installed Win98SE image booting from the local tinywebserver.. this one has an upgrade to 256 cols pci svga and it took about 56 secs.. (with 16 cols significantly shorter in 45 secs) on the i7-32Gb-Chrome-Win10 but I cannot say if that is normal..

https://github.com/user-attachments/assets/f60c5870-83a9-4c69-8864-1ced158ecf7b

Well that's it for now.. I'll keep on testing and shall report any Win98SE floppy issues I may encounter..

**Comment by chschnell** [comment]
> [@chschnell](https://github.com/chschnell) some progress..
> 
> About your site.. `Does this boot for you`: Yes it works if I use a Win 10 machine.. seems that Firefox ESR/Win7 on my laptop errors on `indexedDB.databases function missing`..

Ah, my demo requires the browser to support the [IndexedDB API](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API), but your Firefox ESR/Win7 doesn't support that. I can change it to make this fail silently, but this might take a while.

> `@Win98se`: your commit dóés partly work for a specific situation.. if you remove the floppy controller from devicemanager and reboot.. in contrairy to the v86 mainstream version.. now I can use the A: drive "normally" from the desktop.. instead of going to dos first to be able to access the floppy from desktop.. normal access did not work most of the time before your floppy.js patch but I might be wrong on that.. btw msdos compatibility mode for A: and B: has as result that win98se feels more stable now but still might have other quirks..
> 

That is important feedback, thanks! It really makes sense, so I've tried testing it but... (see below)

>> probably because booting it is so unstable, and also because it boots so slow
> 
> Please explain slow.. this is my on-device installed Win98SE image booting from the local tinywebserver.. this one has an upgrade to 256 cols pci svga and it took about 56 secs.. (with 16 cols significantly shorter in 45 secs) on the i7-32Gb-Chrome-Win10 but I cannot say if that is normal..
> v86_win98se_boot.mp4
> 

...for me it takes 2-3 minutes to boot, and it blue-screens near the end of boot like 3 out of 4 times.

So I wasn't able to reproduce what you describe after spending an hour just to get Win98SE to boot AND to reboot without crashing. I will continue these tests another day.

> Well that's it for now.. I'll keep on testing and shall report any Win98SE floppy issues I may encounter..

Thanks!

**Comment by PTz0uAH** [comment]
@chschnell I wanted to also produce an english version of Win98SE.. for the achievements I had were composed with the dutch version.. I needed to be sure my method for on-device install would be reproduceable.. so why not the english version I thought..

I used a fresh v86 with your floppy patch and my tinywebserver settings and tried both methods described at the win98se topic https://github.com/copy/v86/issues/1359 and failed.. so that was strange.. until I used a 2nd 512MB harddisk with the win98 folder (and root files) copied to which were needed later in the process.. as the CDROM seemed to fail (BUG or WIN98 specific???) later on during the installation where "Windows 98 SE CDROM" was requested..

Phase 1 of the installation bootsequence was `FloppyDrive, HardDrive, CDRom`.. I started "normal" with CDROM support via bootfloppy and after fdisk + format c: the `laptop install` was initiated with: `cd E:\win98` + `setup /C /ie /iv` and all went well until the `remove floppy from diskdrive and press enter` to reboot..  glitch.. the button to eject the floppy was not working so would start over and over again after reboot.. so I broke off the installation after saving the HDA..

Phase 2.. booting v86 from the saved HDA (C:).. I also used the prepared 2nd HDB (D:) and after setting the bootsequence to `HDD/FD/CD` the installation continued.. and went even faster as the files at D:\WIN98 were automatically found.. and finally I was welcomed with the `Welcome to Windows 98` tune..  now NE2000 needed to be removed from devicemanager, the STD-VGA removed.. PCI-VGA-QEMU installed after a lucky reboot while performing the mandatory PNP-BIOS driver update which went relatively well..

In the end the Floppy controller needed to be removed and after at least 1 BSOD-less reboot I saved the HDA image (after shutdown) a couple of times after some modest finetuning of the image..

https://github.com/user-attachments/assets/54c23e55-675d-482c-84af-869feedcba97

So now I have (available) a `pristine` Win98SE_eng image which boots and shuts down with ACPI enabled (dunno if that works).. has at least 1 working Floppy drive.. PCI VGA though the CDROM (win driver thing?) is only usable with small <100MB iso files.. but alez.. thanks to the 2 HDD workaround I could get it installed..

Well now I vastly believe all the win98se problems arise because of timing problems in combination with v86.. Win2K3 is way more capable to handle fluctuations but the PNP IRQ routines of Win98SE booting.. regularly miss out on a device such as the RT8029AS network card.. which should appear after about 14-18 seconds after power-on.. if that time has passed without a network visible.. then you can count on a BSOD during the boot.. it seems Win98SE is extremely picky so we need some tactical tweaks to not make it into a desillusional ordeal..

I do not now if your changes also affected the very annoying CDROM issues but one needs a stable Win98SE image to be able to check it.. so its a bit awkward I guess..

The good thing is Win98SE Floppy stuff works.. more or less.. its functional yet needs more testing for mediaplayer sometimes does not recognise a path when a midi-file from floppy is double clicked.. while double clicking a textfile on floppy works fine.. copy from/to also.. so I can't wait to test a `diskcopy` from A: to B: or the other way around..

https://github.com/user-attachments/assets/55fd1270-8265-47db-b078-5265c07a86d2

If you need an on-v86-device composed/working & floppy-enabled Win98SE image for making your Win98SE floppy-dev-life somewhat easier.. then you could also focus better on the core-problems imho.. the compressed image is about 64.5 MB in size.. and I 've dropped it into my v86 fork `images/`..

to be continued..

**Comment by chschnell** [comment]
I have come to hold the deep believe that Win98SE is cursed, however thanks for the detailled report!

Much appreciate your guest image file, I downloaded and unpacked its parts, it boots fine (detects some PCI stuff at the end of boot) and stable (hooray!). I did get `fda` to work on the second attempt to insert a disk, but not `fdb`. Anyways this is a nice step forward.

Do you have a link to the Win98SE Setup CD that was used to build this image?

**Comment by PTz0uAH** [comment]
@chschnell I picked this one https://archive.org/details/windows-98-se-retail-english albeit not bootable it installed with the procedure described above.. the key in the last review worked.. so good luck with that..

**Comment by chschnell** [comment]
This issue has been resolved and merged with commit 92ba111.
