### ISSUE TITLE
the command some issues and linux run but no test ok message also if run on-site no modified dos image

### ISSUE THREAD

**Issue by KowloonWalledCityCoin** [copy/v86#73]
Try to use the sample site but the dos image has no way to create a writable image (some comments on the web say there is an option. cannot find it)

The follow the commands using my mac.  It works except some minor typing issues i.e
- make build/libv86.js i.e. you need to use libv86.js not lib86.js 
  (I try just make but it only create something but not all as the tests are not created.
- to run you have to do node ./tests/full/run.js i.e. need the node

Finally the dos tested ok but the linux cannot pass the test: ... still no modifiable disk image to play with

node ./tests/full/run.js
Starting test 1: FreeDOS boot
Passed test: FreeDOS boot
Took 2.067s

Starting test 2: Windows 1.01 boot
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
Passed test: Windows 1.01 boot
Took 1.652s

Starting test 3: Sol OS
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
Passed test: Sol OS
Took 2.641s

Starting test 4: Linux
[    1.330982] io scheduler deadline registered                                 
[    1.350980] io scheduler cfq registered (default)                            
[    1.589981] Real Time Clock Driver v1.12b                                    
[    1.589981] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled         
[    1.619980] serial8250: ttyS0 at I/O 0x3f8 (irq = 4) is a XScale             
[    1.829983] brd: module loaded                                               
[    1.928983] loop: module loaded                                              
[    1.928983] Uniform Multi-Platform E-IDE driver                              
[    1.942982] ide_generic: please use "probe_mask=0x3f" module parameter for pr
obing all legacy ISA IDE ports                                                  
[    2.749025] hda: , ATAPI CD/DVD-ROM drive                                    
[    3.109044] ide0 at 0x1f0-0x1f7,0x3f6 on irq 14                              
[    3.728077] ide1 at 0x170-0x177,0x376 on irq 15                              
[    3.728077] ide-gd driver 1.18                                               
[    3.789075] serio: i8042 KBD port at 0x60,0x64 irq 1                         
[    3.789075] serio: i8042 AUX port at 0x60,0x64 irq 12                        
[    3.898075] TCP cubic registered                                             
[    3.898075] NET: Registered protocol family 17                               
[    3.978072] input: AT Translated Set 2 keyboard as /devices/platform/i8042/se
rio0/input/input0                                                               
[    3.998071] RAMDISK: ext2 filesystem found at block 0                        
[    4.010070] RAMDISK: Loading 3883KiB [1 disk] into ram disk... done.         
[    6.589055] VFS: Mounted root (ext2 filesystem) on device 1:0.               
                                                                                
/root%                                                                          
Test failed: Linux

Expected text "test passed"

**Comment by copy** [comment]
I fixed the typos and an issue that prevented us from downloading modified disk images. Note that the Linux images are cdroms and therefore inherently read-only. The only way to make changes is to create a custom build using [Buildroot](http://buildroot.uclibc.org/).

Regarding the test case issue: I can't reproduce this (and our shiny new [Travis instance](https://travis-ci.org/copy/v86) can't reproduce it either). It seems that the timeout is too low, can you try increasing ([here](https://github.com/copy/v86/blob/12ab621202bde700b2f820128fa4453650ea44da/tests/full/run.js#L59)) it and rerunning the tests? It'll need some more fine-grained checks.

**Comment by KowloonWalledCityCoin** [comment]
Thanks.  I would try other platforms for the make one.

For the writable image can you help to have a way to get that image for dos version.  (I would try the buildroot but dos version would be nice.)  the issue is even stranger as you can do something ok in linux/UNIX if no way to save but you cannot even save a file under dos.  It is not just I cannot find a writable image and still can't but the software work strangely. 

Go to your demos, select the freedos floppy.  Try copy say hello.asm to hello2.asm.  Dir. You can see hello2.asm in the first dir.  But dir again.  It is gone!   Try vim hello.asm and after modify the message of hello world then <Esc> w hello2asm.  It said write but then nothing can be found.  In fact you can w q the original file.  

A new dim to my query but it is the dos mode or the bare metal test which draw me to yours.  I am trying to run a bare metal version which is ok for qemu-system-i386 but not yours.  I wonder whether it is mine issues or yours.  The "os-image" with only a bios call and a hello w asm of 200 bytes cannot be loaded.  The system just say load image 2/3.  (The bare metal one is here - http://farid.hajji.name/blog/2010/05/25/hello-world-on-the-bare-metal/)

**Comment by KowloonWalledCityCoin** [comment]
The above should say under dos vim cannot write to the original freedos floppy; not "can".  Vim would really say it can save to the hello2.asm though, even said it is UNIX style line ending!

**Comment by KowloonWalledCityCoin** [comment]
One more ... I download the freedos image through your image links and use my own local version ... Same situation.  

Need a writable image to start further testing.

**Comment by aaron-elkins** [comment]
Following the .travis.yml on Mac OS X 10.11 El Capitan, and run the test which failed.

```
npm test

> v86@ test /Users/aaron/pullreq/v86
> node tests/full/run.js

Starting test 1: FreeDOS boot
Passed test: FreeDOS boot
Took 2.042s

Starting test 2: Windows 1.01 boot
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
Passed test: Windows 1.01 boot
Took 1.564s

Starting test 3: Sol OS
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
Passed test: Sol OS
Took 2.073s

Starting test 4: Linux
Passed test: Linux
Took 28.283s

Starting test 5: Linux 3
[    7.945504] Freeing initrd memory: 3572K (c3c73000 - c3ff0000)               
[    7.953507] platform rtc_cmos: registered platform RTC device (no PNP device 
found)                                                                          
[    7.978513] microcode: CPU0 sig=0xf63, pf=0x1, revision=0x0                  
[    7.991516] microcode: Microcode Update Driver: v2.00 <tigran@aivazian.fsnet.
co.uk>, Peter Oruba                                                             
[    8.038523] Scanning for low memory corruption every 60 seconds              
[    8.142534] futex hash table entries: 256 (order: 2, 16384 bytes)            
[    8.152537] audit: initializing netlink subsys (disabled)                    
[    8.153537] random: nonblocking pool is initialized                          
[    8.157541] audit: type=2000 audit(1447220420.157:1): initialized            
[    8.215549] HugeTLB registered 4 MB page size, pre-allocated 0 pages         
[    9.303655] VFS: Disk quotas dquot_6.5.2                                     
[    9.316658] Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)       
[    9.565680] NFS: Registering the id_resolver key type                        
[    9.568682] Key type id_resolver registered                                  
[    9.569682] Key type id_legacy registered                                    
[    9.582686] msgmni has been set to 103                                       
[    9.692699] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 2
51)                                                                             
[    9.698703] io scheduler noop registered                                     
[    9.699703] io scheduler deadline registered                                 
[    9.734710] io scheduler cfq registered (default)                            
[    9.764714] pci_hotplug: PCI Hot Plug PCI Core version: 0.5                  
                                                                                
Test failed: Linux 3

Expected text "test passed"
npm ERR! Test failed.  See above for more details.
```

**Comment by aaron-elkins** [comment]
After increasing the timeout of test case `Linux 3`, all passed.

```
npm test

> v86@ test /Users/aaron/pullreq/v86
> node tests/full/run.js

Starting test 1: FreeDOS boot
Passed test: FreeDOS boot
Took 2.095s

Starting test 2: Windows 1.01 boot
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
Passed test: Windows 1.01 boot
Took 1.546s

Starting test 3: Sol OS
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
Passed test: Sol OS
Took 2.045s

Starting test 4: Linux
Passed test: Linux
Took 28.812s

Starting test 5: Linux 3
Passed test: Linux 3
Took 80.064s

Starting test 6: KolibriOS
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
V86Starter.prototype.get_statistics is deprecated. Use events instead.
Passed test: KolibriOS
Took 36.513s


All tests passed!
```

WOW.

**Comment by KowloonWalledCityCoin** [comment]
Ignore the vim instead use fdos\edit as the vim may not be usable.  That edit under fdos is usable.

**Comment by KowloonWalledCityCoin** [comment]
I have checked the fdos image is good in using edit and nasm to do assembly programming in dos box but not in vc86.

**Comment by kwccoin** [comment]
Case closed for the test, it run for me as well under my Macbook.  The time limit is the issue.

I would reopen another one on the read-only drive and the vim not working issues.

BTW can I close the case?

**Comment by copy** [comment]
Yep, we'll continue [here](https://github.com/copy/v86/issues/76).

**Comment by Tanyajackson638** [comment]
<details><summary>Details</summary>
<p>

```shell

``` 

</p>
</details>
